package com.application.apptienda.utils
object Urls {
    const val SWEATER_BLACK = "https://i.ibb.co/PrQSyrC/buzo-negro.png"
    const val SWEATER_BLUE = "https://i.ibb.co/S527wCQ/buzo-azul.png"
    const val SWEATER_RED = "https://i.ibb.co/T4SLD93/buzo-rojo.png"
    const val SWEATER_WHITE = "https://i.ibb.co/bFfnhCN/buzo-blanco.png"
    const val SHIRT_BLACK = "https://i.ibb.co/42YS97W/camisa-negra.png"
    const val SHIRT_WHITE = "https://i.ibb.co/9bmqRgb/camisa-blanca.png"
    const val SHIRT_RED = "https://i.ibb.co/Qpz7ZXN/camisa-roja.png"
    const val SHIRT_BLUE = "https://i.ibb.co/yyBFH5q/camisa-azul.png"

    const val GIRL_PERFIL1 = "https://i.ibb.co/gJQS3Gx/girl-perfil1.png"
    const val GIRL_PERFIL2 = ""
    const val GIRL_PERFIL3 = ""

    const val GIRL_HAIR1 = "https://i.ibb.co/BVDD81F/cabello-1.png"
    const val GIRL_HAIR2 = "https://i.ibb.co/BLyfnQT/GIRL-HAIR2.png"
    const val GIRL_HAIR3 = "https://i.ibb.co/B4WzYVt/GIRL-HAIR3.png"

    // GIRL PERFIL 1
    const val GIRL_PERFIL1_HAIR1_BLACK = "https://i.ibb.co/BGM7BF7/girl-perfil1-hair1.png"
    const val GIRL_PERFIL1_HAIR1_BROWN = "https://i.ibb.co/P1JWC0J/girl-perfil1-hair1-brown.png"
    const val GIRL_PERFIL1_HAIR1_RED = "https://i.ibb.co/t8kf3q8/girl-perfil1-hair1-red.png"

    const val GIRL_PERFIL1_HAIR2_BLACK = "https://i.ibb.co/94sh45p/GIRL-PERFIL1-HAIR2-BLACK.png"
    const val GIRL_PERFIL1_HAIR2_BROWN = "https://i.ibb.co/r2Sc91p/GIRL-PERFIL1-HAIR2-BROWN.png"
    const val GIRL_PERFIL1_HAIR2_RED = "https://i.ibb.co/0Dnqw9Y/GIRL-PERFIL1-HAIR2-RED.png"

    const val GIRL_PERFIL1_HAIR3_BLACK = "https://i.ibb.co/BwMQ6YG/GIRL-PERFIL1-HAIR3-BLACK.png"
    const val GIRL_PERFIL1_HAIR3_BROWN = "https://i.ibb.co/VmG73q7/GIRL-PERFIL1-HAIR3-BROWN.png"
    const val GIRL_PERFIL1_HAIR3_RED = "https://i.ibb.co/kmTTn5n/GIRL-PERFIL1-HAIR3-RED.png"

    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLACK_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_WHITE_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLUE_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_RED_ANIMADO1 = ""

    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLACK_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_WHITE_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLUE_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_RED_ANIMADO2 = ""

    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLACK_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_WHITE_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_BLUE_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SWEATER_RED_ANIMADO3 = ""

    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLACK_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_WHITE_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLUE_ANIMADO1 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_RED_ANIMADO1 = ""

    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLACK_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_WHITE_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLUE_ANIMADO2 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_RED_ANIMADO2 = ""

    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLACK_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_WHITE_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_BLUE_ANIMADO3 = ""
    const val GIRL_PERFIL1_HAIR1_BLACK_SHIRT_RED_ANIMADO3 = ""

    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLACK_ANIMADO1 = "https://i.ibb.co/1XLRJ66/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLACK-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_WHITE_ANIMADO1 = "https://i.ibb.co/J3KKSFd/GIRL-PERFIL1-HAIR1-RED-SWEATER-WHITE-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLUE_ANIMADO1 = "https://i.ibb.co/c6xQqxN/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLUE-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_RED_ANIMADO1 = "https://i.ibb.co/CvqydWG/GIRL-PERFIL1-HAIR1-RED-SWEATER-RED-ANIMADO1.png"

    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLACK_ANIMADO2 = "https://i.ibb.co/XyDL8b3/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLACK-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_WHITE_ANIMADO2 = "https://i.ibb.co/d7Zzsjt/GIRL-PERFIL1-HAIR1-RED-SWEATER-WHITE-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLUE_ANIMADO2 = "https://i.ibb.co/tCjJg0p/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLUE-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_RED_ANIMADO2 = "https://i.ibb.co/MDGXYv7/GIRL-PERFIL1-HAIR1-RED-SWEATER-RED-ANIMADO2.png"

    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLACK_ANIMADO3 = "https://i.ibb.co/3vMC0Xt/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLACK-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_WHITE_ANIMADO3 = "https://i.ibb.co/RgBksJF/GIRL-PERFIL1-HAIR1-RED-SWEATER-WHITE-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_BLUE_ANIMADO3 = "https://i.ibb.co/QjkQdwj/GIRL-PERFIL1-HAIR1-RED-SWEATER-BLUE-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SWEATER_RED_ANIMADO3 = "https://i.ibb.co/qBtwVbC/GIRL-PERFIL1-HAIR1-RED-SWEATER-RED-ANIMADO3.png"

    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLACK_ANIMADO1 = "https://i.ibb.co/YhBbcCw/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLACK-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_WHITE_ANIMADO1 = "https://i.ibb.co/VjKZ9n3/GIRL-PERFIL1-HAIR1-RED-SHIRT-WHITE-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLUE_ANIMADO1 = "https://i.ibb.co/F509BPf/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLUE-ANIMADO1.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_RED_ANIMADO1 = "https://i.ibb.co/pbXHMyr/GIRL-PERFIL1-HAIR1-RED-SHIRT-RED-ANIMADO1.png"

    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLACK_ANIMADO2 = "https://i.ibb.co/m9CkDWv/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLACK-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_WHITE_ANIMADO2 = "https://i.ibb.co/kXmpmPM/GIRL-PERFIL1-HAIR1-RED-SHIRT-WHITE-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLUE_ANIMADO2 = "https://i.ibb.co/hLtDm50/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLUE-ANIMADO2.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_RED_ANIMADO2 = "https://i.ibb.co/RbMY6vg/GIRL-PERFIL1-HAIR1-RED-SHIRT-RED-ANIMADO2.png"

    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLACK_ANIMADO3 = "https://i.ibb.co/FJBmg6t/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLACK-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_WHITE_ANIMADO3 = "https://i.ibb.co/FBHV5vv/GIRL-PERFIL1-HAIR1-RED-SHIRT-WHITE-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_BLUE_ANIMADO3 = "https://i.ibb.co/HtBMkkb/GIRL-PERFIL1-HAIR1-RED-SHIRT-BLUE-ANIMADO3.png"
    const val GIRL_PERFIL1_HAIR1_RED_SHIRT_RED_ANIMADO3 = "https://i.ibb.co/T4hnXVW/GIRL-PERFIL1-HAIR1-RED-SHIRT-RED-ANIMADO3.png"
}
